### ISSUE TITLE
ValueError: ("the use of non-builtin globals isn't supported")

### ISSUE THREAD

**Issue by hah86** [pytest-dev/pytest-cloud#21] opened 2020-09-11 10:23 UTC
Getting below error. please help me out to proceed further.

(workvenv) bash-3.2$ pytest tests/ --cloud-node=hah@1.2.3.4 --cloud-chdir=/home/hah --cloud-max-processes=2 --rsyncdir=.
Detected root dir: /Users/harish/Work/PPMPro/automation
Detecting connectable test nodes...
NODES LEN 1
SPECS ssh=hah@1.2.3.4//id=1.2.3.4//chdir=/home/hah//python=python3.7
group 0
Node hah@1.2.3.4
HOST IS hah@1.2.3.4
Host 1.2.3.4
Found 1 connectable test nodes: {'hah@1.2.3.4'}
RSyncing directory structure
**rsync: -arHAXx: unknown option
rsync error: syntax or usage error (code 1) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/main.c(1337) [client=2.6.9]
RSync finished**

Traceback (most recent call last):
  File "/Users/harish/Work/workvenv/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 92, in main
    config=config
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 136, in pytest_cmdline_main
    check_options(config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 340, in check_options
    config=config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 312, in get_nodes_specs
    for node, hst in node_specs))
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 312, in <genexpr>
    for node, hst in node_specs))
KeyError: '1.2.3.4'

**Comment by hah86** [comment] 2020-09-11 13:33
Looks like in plugin.py file at line number 254 **group = execnet.Group()** this is giving empty list
post that it is being used at **make_gateway(group, spec)** which makes call to **make_gateway**

@timeout_decorator.timeout(3)
def make_gateway(group, spec):
    """Make a gateway."""
    group.makegateway(spec)

since group is empty list , it is causing issue here ?

**Comment by hah86** [comment] 2020-09-11 14:08
have increased timeout to 10 in **make_gateway** function. Now getting different error as below


RSync finished
Traceback (most recent call last):
  File "/Users/harish/Work/workvenv/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 92, in main
    config=config
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 136, in pytest_cmdline_main
    check_options(config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 343, in check_options
    config=config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 301, in get_nodes_specs
    patches.activate_env, virtualenv_path=virtualenv_path, develop_eggs=develop_eggs).waitclose()
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/execnet/multi.py", line 217, in remote_exec
    channels.append(gw.remote_exec(source, **kwargs))
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/execnet/gateway.py", line 119, in remote_exec
    source = _source_of_function(source)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/execnet/gateway.py", line 211, in _source_of_function
    used_globals,
ValueError: ("the use of non-builtin globals isn't supported", ['execfile', 'egg', 'egg'])

**Comment by hramamurthy** [comment] 2020-09-14 04:59
post this **ValueError: ("the use of non-builtin globals isn't supported", ['execfile', 'egg', 'egg'])**  unable to ssh to remote server as it looks like deleting id_rsa.pub key from remote server

**Comment by hah86** [comment] 2020-09-15 02:47
post this **ValueError: ("the use of non-builtin globals isn't supported", ['execfile', 'egg', 'egg'])** unable to ssh to remote server as it looks like deleting id_rsa.pub key from remote server

**Comment by bubenkoff** [comment] 2020-09-15 10:26
first, as you're using mac, rsync doesn't accept the same options as the native rsync shipped with macos.
You can install rsync from brew to get the same behavior (and make sure it's preferred in the PATH of course)

**Comment by hah86** [comment] 2020-09-15 10:31
Yes, i have installed rsync using brew. post that sync started working as i could see files have been copied to remote server

**Comment by bubenkoff** [comment] 2020-09-15 10:33
@hah86 so does it all work in the end or you have some other error?

**Comment by hah86** [comment] 2020-09-15 10:35
currently i am getting this below error
**ValueError: ("the use of non-builtin globals isn't supported", ['execfile', 'egg', 'egg'])** 

RSync finished
Traceback (most recent call last):
File "/Users/harish/Work/workvenv/bin/pytest", line 8, in
sys.exit(main())
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/_pytest/config/init.py", line 92, in main
config=config
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in call
return self._hookexec(self, self.get_hookimpls(), kwargs)
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
return self._inner_hookexec(hook, methods, kwargs)
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in
firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
return outcome.get_result()
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
raise ex[1].with_traceback(ex[2])
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
res = hook_impl.function(*args)
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 136, in pytest_cmdline_main
check_options(config)
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 343, in check_options
config=config)
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 301, in get_nodes_specs
patches.activate_env, virtualenv_path=virtualenv_path, develop_eggs=develop_eggs).waitclose()
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/execnet/multi.py", line 217, in remote_exec
channels.append(gw.remote_exec(source, **kwargs))
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/execnet/gateway.py", line 119, in remote_exec
source = _source_of_function(source)
File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/execnet/gateway.py", line 211, in _source_of_function
used_globals,
ValueError: ("the use of non-builtin globals isn't supported", ['execfile', 'egg', 'egg'])


Once it fails with above failure, unable to ssh to remote server as it looks like deleting id_rsa.pub key from remote server

**Comment by bubenkoff** [comment] 2020-09-15 10:47
please provide the full log

**Comment by hah86** [comment] 2020-09-15 10:56
(workvenv) bash-3.2$ pytest tests/ --cloud-node=harish@1.2.3.4 --cloud-chdir=/home/harish --cloud-virtualenv-path=/Users/harish/Work/workvenv --cloud-max-processes=2 --rsyncdir=.
Detected root dir: /Users/harish/Work/PPMPro/automation
Detecting connectable test nodes...
NODES LEN 1
SPECS ssh=harish@1.2.3.4//id=1.2.3.4//chdir=/home/harish//python=python3.7
group 0
Node harish@1.2.3.4
Host 1.2.3.4
NODE SPECS [('harish@1.2.3.4', '1.2.3.4')]
Found 1 connectable test nodes: {'harish@1.2.3.4'}
RSyncing directory structure
RSync finished
/Users/harish/Work/workvenv/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/Users/harish/Work/workvenv/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 92, in main
    config=config
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 136, in pytest_cmdline_main
    check_options(config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 343, in check_options
    config=config)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/pytest_cloud/plugin.py", line 301, in get_nodes_specs
    patches.activate_env, virtualenv_path=virtualenv_path, develop_eggs=develop_eggs).waitclose()
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/execnet/multi.py", line 217, in remote_exec
    channels.append(gw.remote_exec(source, **kwargs))
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/execnet/gateway.py", line 119, in remote_exec
    source = _source_of_function(source)
  File "/Users/harish/Work/workvenv/lib/python3.7/site-packages/execnet/gateway.py", line 211, in _source_of_function
    used_globals,
ValueError: ("the use of non-builtin globals isn't supported", ['execfile', 'egg', 'egg'])

**Comment by bubenkoff** [comment] 2020-09-15 10:59
please remove the chdir parameter and try again?

**Comment by bubenkoff** [comment] 2020-09-15 11:00
does plain pytest-xdist work btw?

**Comment by hah86** [comment] 2020-09-15 11:32
yeah pytest-xdist with n=4 or 5 it works fine

**Comment by bubenkoff** [comment] 2020-09-15 11:46
I mean the remote xdist of course

**Comment by hah86** [comment] 2020-09-30 03:37
using xdist tests are not running on remote and it is stuck at this place
(workvenv) bash-3.2$ pytest -d --tx ssh=hramamurthy@1.2.3.4 --rsyncdir=.
=========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 3.7.7, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
rootdir: /Users/harish/Work/PPMPro/automation, configfile: pytest.ini, testpaths: tests
plugins: cloud-5.0.0, metadata-1.10.0, repeat-0.8.0, variables-1.9.0, html-2.1.1, xdist-2.1.0, forked-1.1.3
gw0 C

**Comment by hah86** [comment] 2020-09-30 03:43
Regarding this error **ValueError: ("the use of non-builtin globals isn't supported", ['execfile', 'egg', 'egg'])**
Looks like it is trying to install some packages from ini file because **get_develop_eggs**  in plugin.py file is returning empty list. 
Please let me know how/where to specify below ini file options
cloud_develop_eggs
Optional list of python package paths to install in development mode on remote side. Required to be inside of the project root directory.

**Comment by bubenkoff** [comment] 2020-09-30 03:50
@hah86 you'll need to have a working setup with just plain xdist first - refer to pytest-xdist docs and it's project issues
about the the use of non-builtin globals - so do you have the cloud_develop_eggs param set in the ini file or not?

**Comment by hah86** [comment] 2020-09-30 03:53
pytest-xdist alone works fine without any issues. However Sending tests to remote SSH accounts is not working and looks like it is stuck forever as it is not proceeding any further after test session starts
i have not set cloud_develop_eggs param in the ini file as it is said optional list.. i assume this is requirements.txt file path. please let me know if it is otherwise

**Comment by bubenkoff** [comment] 2020-10-02 15:43
@dasm can you please look into it, may be you can help

**Comment by dasm** [comment] 2020-10-02 16:55
I've been able to reproduce this error for py3. I also was able to run the same code for py2, and it doesn't show this problem.

It doesn't seem to be a problem with missing `develop_egg`, because for the py2, it is not showing to be an issue.

Still investigating.

**Comment by dasm** [comment] 2020-10-02 18:28
@bubenkoff it seems like `activate_env` inside `pytest_cloud/patches.py` requires some work towards `python3-only` environment.

First thing:
1. `python3` doesn't have `execfile`. During the time, when execnet is trying to run patch, it is detecting missing `execfile` from `__builtin__`, breaking and causing issues.
1. similar thing for `egg`, however it can be easily addressed by `egg = None` before loop
1. `python3 venv` doesn't have `activate_this.py` which also needs to be changed.

Do you want to bite this bullet, @bubenkoff ?

**Comment by bubenkoff** [comment] 2020-10-02 23:57
@dasm thank you for looking into this
do you use this project in any of your py3 based projects then?
looks like it's simply broken for py3 and we need a user who can fix and verify it all (I don't have an ongoing python project for quite some time already)

**Comment by dasm** [comment] 2020-10-03 00:02
@bubenkoff I can work on that.

**Comment by bubenkoff** [comment] 2020-10-03 00:04
@dasm appreciate your help a lot!

**Closed as completed** 2020-10-05 17:33 UTC
